apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ .Values.deploy_folder }}-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#alerts-test\", \"username\": \"hello\", \"text\": \"App Sync succeeded\", \"icon_emoji\": \":ghost:\"}"
          - "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ .Values.deploy_folder }}-slack-notification-fail-
  annotations:
    argocd.argoproj.io/hook: SyncFail
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#alerts-test\", \"username\": \"hello\", \"text\": \"App Sync failed\", \"icon_emoji\": \":ghost:\"}"
          - "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 2