apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployment-root-test
  namespace: argocd
  labels:
    rm_cicd_applicationset: test
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jngbot/argocd-playground.git'
    path: charts/deployment-manager
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
