apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
  # labels:
  #   environment: prod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/j6nca/helm-charts.git'
    path: charts/test-app
    targetRevision: HEAD
    # helm:
    #   valueFiles:
    #     - values-prod.yaml
    kustomize:
      patches:
      - target:
          kind: Deployment
          name: test-app
        patch: |
          - op: add
            path: metadata/labels
            labels:
            - pairs:
                my_test_label1: argocd
                my_test_label2: main
                my_test_label3: test-app
              includeSelectors: false
              includeTemplates: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: playground
