apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
  labels:
    rm_cicd_applicationset: prod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/j6nca/helm-charts.git'
    path: charts/test-app
    targetRevision: HEAD
    # helm:
    #   valueFiles:
    #     - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
